### ISSUE TITLE
asn.__file__ is missing

### ISSUE THREAD

**Issue by darshitajain** [mees/Adversarial-Skill-Networks#4]
![asn_err](https://user-images.githubusercontent.com/19747895/121315687-34666c80-c926-11eb-947c-56e5f748bcca.png)

**Comment by mees** [comment]
that's weird, did you run `pip install -e .` to install asn in your virtual environment as stated in the instructions? Maybe try importing asn in a python shell to check if it works.

**Comment by darshitajain** [comment]
Thank you for your response.

I commented out that line then the code was working fine.
